package DateTime.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDate = createDescriptorForDate();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDate);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Date:
        return myConceptDate;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForDate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DateTime", "Date", 0x2bc0050f69d04772L, 0x99033735cb700947L, 0x53eb98c308d9b15eL);
    b.class_(false, false, false);
    b.origin("r:f80e0c3f-a508-4694-811e-d58cf738628b(DateTime.structure)/6047094888109551966");
    b.prop("day", 0x53eb98c308d9b439L, "6047094888109552697");
    b.prop("month", 0x53eb98c308d9b43bL, "6047094888109552699");
    b.prop("year", 0x53eb98c308d9b43eL, "6047094888109552702");
    return b.create();
  }
}
