package Objects.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myEvent__BehaviorDescriptor = new Event__BehaviorDescriptor();
  private final BHDescriptor myPropertyValue__BehaviorDescriptor = new PropertyValue__BehaviorDescriptor();
  private final BHDescriptor myValue__BehaviorDescriptor = new Value__BehaviorDescriptor();
  private final BHDescriptor myStringValue__BehaviorDescriptor = new StringValue__BehaviorDescriptor();
  private final BHDescriptor myDateValue__BehaviorDescriptor = new DateValue__BehaviorDescriptor();
  private final BHDescriptor mySetObjectInstances__BehaviorDescriptor = new SetObjectInstances__BehaviorDescriptor();
  private final BHDescriptor myObjectInstanceValue__BehaviorDescriptor = new ObjectInstanceValue__BehaviorDescriptor();
  private final BHDescriptor myObjectInstance__BehaviorDescriptor = new ObjectInstance__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (index_846f5o_a0l.index(cncpt)) {
      case 0:
        return myDateValue__BehaviorDescriptor;
      case 1:
        return myEvent__BehaviorDescriptor;
      case 2:
        return myObjectInstance__BehaviorDescriptor;
      case 3:
        return myObjectInstanceValue__BehaviorDescriptor;
      case 4:
        return myPropertyValue__BehaviorDescriptor;
      case 5:
        return mySetObjectInstances__BehaviorDescriptor;
      case 6:
        return myStringValue__BehaviorDescriptor;
      case 7:
        return myValue__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex index_846f5o_a0l = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x309151bb6753ecc8L), MetaIdFactory.conceptId(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x24097a55b88d7404L), MetaIdFactory.conceptId(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x53eb98c308da284cL), MetaIdFactory.conceptId(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x309151bb67599d18L), MetaIdFactory.conceptId(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x309151bb6753eb39L), MetaIdFactory.conceptId(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x309151bb67587108L), MetaIdFactory.conceptId(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x309151bb6753ecb1L), MetaIdFactory.conceptId(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x309151bb6753eb3cL)).seal();
}
