package Objects.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class SetObjectInstances_Constraints extends BaseConstraintsDescriptor {
  public SetObjectInstances_Constraints() {
    super(MetaAdapterFactory.getConcept(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x309151bb67587108L, "Objects.structure.SetObjectInstances"));
  }

}
