package ObjectType.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myProperty__BehaviorDescriptor = new Property__BehaviorDescriptor();
  private final BHDescriptor myRelation__BehaviorDescriptor = new Relation__BehaviorDescriptor();
  private final BHDescriptor myAbstractProperty__BehaviorDescriptor = new AbstractProperty__BehaviorDescriptor();
  private final BHDescriptor myMethod__BehaviorDescriptor = new Method__BehaviorDescriptor();
  private final BHDescriptor myObjectEventModel__BehaviorDescriptor = new ObjectEventModel__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (index_846f5o_a0i.index(cncpt)) {
      case 0:
        return myAbstractProperty__BehaviorDescriptor;
      case 1:
        return myMethod__BehaviorDescriptor;
      case 2:
        return myObjectEventModel__BehaviorDescriptor;
      case 3:
        return myProperty__BehaviorDescriptor;
      case 4:
        return myRelation__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex index_846f5o_a0i = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308dd6c5cL), MetaIdFactory.conceptId(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L), MetaIdFactory.conceptId(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c30915f01aL), MetaIdFactory.conceptId(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308d9b121L), MetaIdFactory.conceptId(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308dae2f3L)).seal();
}
