package Specification.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptSpecification = createDescriptorForSpecification();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptSpecification);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Specification:
        return myConceptSpecification;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForSpecification() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Specification", "Specification", 0x40b7f9cd2341434aL, 0xa23eae796e75a4d8L, 0x53eb98c308da2079L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f78cea42-5ad4-4a39-960f-415f5b1aa24d(Specification.structure)/6047094888109580409");
    b.aggregate("objecttypes", 0x53eb98c308da207aL).target(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308d9b120L).optional(true).ordered(true).multiple(true).origin("6047094888109580410").done();
    b.aggregate("eventtypes", 0x53eb98c308e17debL).target(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e17cfbL).optional(true).ordered(true).multiple(true).origin("6047094888110063083").done();
    b.aggregate("OET", 0x53eb98c308e94356L).target(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e69c16L).optional(true).ordered(true).multiple(false).origin("6047094888110572374").done();
    return b.create();
  }
}
