package Objects.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int DateValue = 0;
  public static final int ObjectInstance = 1;
  public static final int ObjectInstanceValue = 2;
  public static final int PropertyValue = 3;
  public static final int SetObjectInstances = 4;
  public static final int StringValue = 5;
  public static final int Validity = 6;
  public static final int Value = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xcab25696e7a84bc6L, 0x80eb639299db8d07L);
    builder.put(0x309151bb6753ecc8L, DateValue);
    builder.put(0x53eb98c308da284cL, ObjectInstance);
    builder.put(0x309151bb67599d18L, ObjectInstanceValue);
    builder.put(0x309151bb6753eb39L, PropertyValue);
    builder.put(0x309151bb67587108L, SetObjectInstances);
    builder.put(0x309151bb6753ecb1L, StringValue);
    builder.put(0x53eb98c308d9b159L, Validity);
    builder.put(0x309151bb6753eb3cL, Value);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
