package Specification.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import Objects.behavior.SetObjectInstances__BehaviorDescriptor;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import Objects.behavior.ObjectInstance__BehaviorDescriptor;
import Objects.behavior.Event__BehaviorDescriptor;

public class Simulation {
  public static void executeEvent(SNode event, SNode data) {
    System.out.println("executeEvent " + event);
    for (SNode method : ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(SLinkOperations.getTarget(event, MetaAdapterFactory.getReferenceLink(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x24097a55b88d7404L, 0x24097a55b88d7405L, "eventType")), MetaAdapterFactory.getConcept(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c30915f01aL, "ObjectType.structure.ObjectEventModel"), false, false), MetaAdapterFactory.getContainmentLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c30915f01aL, 0x53eb98c3090b989dL, "methods")))) {
      if (SLinkOperations.getTarget(method, MetaAdapterFactory.getReferenceLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L, 0x53eb98c308e23c23L, "eventType")) == SLinkOperations.getTarget(event, MetaAdapterFactory.getReferenceLink(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x24097a55b88d7404L, 0x24097a55b88d7405L, "eventType"))) {
        executeMethod(event, method, data);
      }
    }
  }
  public static void executeMethod(SNode event, SNode method, SNode data) {
    System.out.println("executeMethod " + event + " " + method);
    if (SPropertyOperations.hasValue(method, MetaAdapterFactory.getProperty(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L, 0x53eb98c3090198b9L, "type"), "C", null)) {
      executeCreateMethod(event, method, data);
    }
    if (SPropertyOperations.hasValue(method, MetaAdapterFactory.getProperty(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L, 0x53eb98c3090198b9L, "type"), "M", null)) {
    }
    if (SPropertyOperations.hasValue(method, MetaAdapterFactory.getProperty(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L, 0x53eb98c3090198b9L, "type"), "E", null)) {
    }
  }
  public static void executeCreateMethod(SNode event, final SNode method, SNode data) {
    System.out.println("executeCreateMethod " + event + " " + SLinkOperations.getTarget(method, MetaAdapterFactory.getReferenceLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L, 0x53eb98c3090198a4L, "objectType")) + " " + SLinkOperations.getChildren(method, MetaAdapterFactory.getContainmentLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L, 0x40f5cd89ad003c7cL, "assigments")));
    SNode objectInstance = SetObjectInstances__BehaviorDescriptor.newObjectInstance_id1LSSMgyoRuk.invoke(ListSequence.fromList(SLinkOperations.getChildren(data, MetaAdapterFactory.getContainmentLink(0x40b7f9cd2341434aL, 0xa23eae796e75a4d8L, 0x309151bb6758e0b8L, 0x309151bb6758e9f8L, "sets"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SLinkOperations.getTarget(it, MetaAdapterFactory.getReferenceLink(0xcab25696e7a84bc6L, 0x80eb639299db8d07L, 0x309151bb67587108L, 0x309151bb675aa631L, "objecttype")) == SLinkOperations.getTarget(method, MetaAdapterFactory.getReferenceLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L, 0x53eb98c3090198a4L, "objectType"));
      }
    }).first());
    for (SNode assignment : ListSequence.fromList(SLinkOperations.getChildren(method, MetaAdapterFactory.getContainmentLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c22L, 0x40f5cd89ad003c7cL, "assigments")))) {
      System.out.println("assignment " + assignment);
      {
        final SNode inputPropertyReference = SLinkOperations.getTarget(assignment, MetaAdapterFactory.getContainmentLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x40f5cd89acfdd152L, 0x40f5cd89ad003c77L, "theAssigned"));
        if (SNodeOperations.isInstanceOf(inputPropertyReference, MetaAdapterFactory.getConcept(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x40f5cd89acfdd157L, "ObjectType.structure.InputPropertyReference"))) {
          System.out.println("inputPropertyReference " + SLinkOperations.getTarget(SLinkOperations.getTarget(inputPropertyReference, MetaAdapterFactory.getReferenceLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x40f5cd89acfdd157L, 0x40f5cd89acfdd158L, "inputProperty")), MetaAdapterFactory.getReferenceLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x3b484aadf59a7833L, 0x3b484aadf59a7834L, "property")));
          ObjectInstance__BehaviorDescriptor.assignValueToProperty_id1LSSMgypSNC.invoke(objectInstance, SLinkOperations.getTarget(assignment, MetaAdapterFactory.getReferenceLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x40f5cd89acfdd152L, 0x40f5cd89acfdd153L, "assignedTo")), SNodeOperations.copyNode(Event__BehaviorDescriptor.getPropertyValue_id1LSSMgyqihi.invoke(event, SLinkOperations.getTarget(inputPropertyReference, MetaAdapterFactory.getReferenceLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x40f5cd89acfdd157L, 0x40f5cd89acfdd158L, "inputProperty")))));
        }
      }
    }
  }
}
