package ObjectType.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.scope.ListScope;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.SNodePointer;

public class AbstractPropertyReference_Constraints extends BaseConstraintsDescriptor {
  public AbstractPropertyReference_Constraints() {
    super(MetaAdapterFactory.getConcept(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c29L, "ObjectType.structure.AbstractPropertyReference"));
  }

  @Override
  public boolean hasOwnDefaultScopeProvider() {
    return true;
  }
  @Override
  public ReferenceScopeProvider getDefaultScopeProvider() {
    return new BaseScopeProvider() {
      @Override
      public SNodeReference getSearchScopeValidatorNode() {
        return breakingNode_k7mw7p_a0a0a0a0a3;
      }
      @Override
      public Scope createScope(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
        {
          List<SNode> abstractProperties = new ArrayList<SNode>();
          {
            final SNode objectType = _context.getContextNode();
            if (SNodeOperations.isInstanceOf(objectType, MetaAdapterFactory.getConcept(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308d9b120L, "ObjectType.structure.ObjectType"))) {
              for (SNode property : ListSequence.fromList(SLinkOperations.getChildren(objectType, MetaAdapterFactory.getContainmentLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308d9b120L, 0x53eb98c308d9bb25L, "properties")))) {
                ListSequence.fromList(abstractProperties).addElement(property);
              }
            }
          }
          return ListScope.forNamedElements(abstractProperties);
        }
      }
    };
  }
  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(MetaAdapterFactory.getReferenceLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c29L, 0x53eb98c308e23c2aL, "abstractProperty"), new BaseReferenceConstraintsDescriptor(MetaIdFactory.refId(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308e23c29L, 0x53eb98c308e23c2aL), this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_k7mw7p_a0a0a0a0a1a0b0a1a4;
          }
          @Override
          public Scope createScope(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            {
              List<SNode> abstractProperties = new ArrayList<SNode>();
              {
                final SNode objectType = _context.getContextNode();
                if (SNodeOperations.isInstanceOf(objectType, MetaAdapterFactory.getConcept(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308d9b120L, "ObjectType.structure.ObjectType"))) {
                  for (SNode property : ListSequence.fromList(SLinkOperations.getChildren(objectType, MetaAdapterFactory.getContainmentLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308d9b120L, 0x53eb98c308d9bb25L, "properties")))) {
                    ListSequence.fromList(abstractProperties).addElement(property);
                  }
                }
              }
              {
                final SNode objectType = SNodeOperations.getParent(_context.getContextNode());
                if (SNodeOperations.isInstanceOf(objectType, MetaAdapterFactory.getConcept(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308d9b120L, "ObjectType.structure.ObjectType"))) {
                  for (SNode property : ListSequence.fromList(SLinkOperations.getChildren(objectType, MetaAdapterFactory.getContainmentLink(0x2f2b62d8f25248ccL, 0x8e79f44966765664L, 0x53eb98c308d9b120L, 0x53eb98c308d9bb25L, "properties")))) {
                    ListSequence.fromList(abstractProperties).addElement(property);
                  }
                }
              }

              return ListScope.forNamedElements(abstractProperties);
            }
          }
        };
      }
    });
    return references;
  }
  private static SNodePointer breakingNode_k7mw7p_a0a0a0a0a3 = new SNodePointer("r:94f5ec65-5a74-4f23-a86b-ad49d49f5f1d(ObjectType.constraints)", "4271746357562397394");
  private static SNodePointer breakingNode_k7mw7p_a0a0a0a0a1a0b0a1a4 = new SNodePointer("r:94f5ec65-5a74-4f23-a86b-ad49d49f5f1d(ObjectType.constraints)", "4271746357562391038");
}
